/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.freewebmovement.peer
class Main {
    val greeting: String
        get() {
            return "Hello Peer!"
        }
}


fun main() {
    println(Main().greeting)
//    val app = MyApp.getInstance()
//    app.ipList = IPList()
//    app.client = PeerClient()
//    var server =
//    PeerServer.start(app, "0.0.0.0", app.settings.network.localServerPort)
}
